### ISSUE TITLE
Isolate main/test/platform classes

### ISSUE THREAD

**Issue by sormuras** [sormuras/junit-platform-manager#1]
There should be three classloaders:

- Platform + all TestEngine implementation classes
- Main classes
- Test classes

From @rfscholte in https://github.com/sormuras/junit-platform-maven-plugin/issues/4
> I created one a long time ago with @britter at ApacheCon, I think he still has it somewhere. Right now everything is one 1 classpath, which means that "main" code can access the testclasses and engine, which is not desired. Same counts for "test" code: it should not be able to access engine code.
I use the word "access" on purpose, because maven scopes prevent you from doing this during compilation, but it is still possible via reflection.

Project outlining the shared classloader issue: https://github.com/britter/junit-cl

**Comment by nipafx** [comment]
@sormuras regarding reflection in the module system:

* JPMS encapsulation does not limit visibility (you can load internal classes, get private methods, etc.) but accessibility (you can not access/invoke them). This explains why `loadClass` works, but `newInstance` doesn't.
* JPMS encapsulation places the same limitations on reflection as on binary access - except for one detail: reflection adds a readability edge. As a consequence, a module can reflectively access all accessible code in any module it can see, so main, test, and engine can all access each other if they end up in the same layer.

And a word on class loaders vs layers: Layers have no "isolative powers" of their own - they rely on class loaders for isolation. Maybe the cases `CLASSIC` and `MODULAR` only need to differ in details, i.e. whether JARs/modules are found by a `URLClassLoader` directly (if that works) or a `ModuleFinder`.

**Comment by nipafx** [comment]
> Meaning, when you know/scan/guess the internals of a module you may you may see everything? Ergo, no change compared the the classpath world?

Yes. And because reflection adds a readability edge, accessible members (public and exported) can be invoked. That means test code can reflectively use public Jupiter API.

**Comment by sormuras** [comment]
Crazy. Even with `--illegal-access=deny` passed at the Java command line? I guess, yes.

**Comment by nipafx** [comment]
Yes because it's no illegal access. :wink:

**Comment by sormuras** [comment]
After some experimentations a contrived sample project could look like this.

### Paths

```
Main (scope=compile) Paths
  classes
  asm-7.0.jar

Test (scope=test) Paths
  test-classes
  junit-jupiter-api-5.3.2.jar
  apiguardian-api-1.0.0.jar
  opentest4j-1.1.1.jar
  junit-platform-commons-1.3.2.jar

JUnit Platform Paths
  junit-platform-launcher-1.3.2.jar
  junit-platform-engine-1.3.2.jar
  junit-jupiter-engine-5.3.2.jar
```  


### Class loader layout

- jdk.internal.loader.ClassLoaders$AppClassLoader@6e5e91e4]
- TCCL(ClassRealm[extension>de.sormuras:junit-platform-maven-plugin:0.811.0-SNAPSHOT)
  - Loader(java.net.URLClassLoader@**6a12c7a8**) "Main"
    - Loader(java.net.URLClassLoader@_161aa04a_) "Test
      - Loader(java.net.URLClassLoader@`436bd4df`)  "JUnit Platform"

`Object` loaded by null
`Opcodes` loaded by java.net.URLClassLoader@**6a12c7a8**
`JUnitException` loaded by java.net.URLClassLoader@_161aa04a_
`Launcher` loaded by java.net.URLClassLoader@`436bd4df`
