### ISSUE TITLE
Generate equals()/hashCode() and toString() methods

### ISSUE THREAD

**Issue by sormuras** [sormuras/junit-platform-manager#11]
Generate equals()/hashCode() and toString() methods ... with ByteBuddy and its Maven Plugin. Is this possible, @raphw?

- https://github.com/sormuras/junit-platform-isolator/blob/master/junit-platform-isolator-base-8/src/main/java/de/sormuras/junit/platform/isolator/Configuration.java#L72-L109
- https://github.com/sormuras/junit-platform-isolator/blob/master/junit-platform-isolator-base-8/src/main/java/de/sormuras/junit/platform/isolator/Configuration.java#L182-L234
- https://github.com/sormuras/junit-platform-isolator/blob/master/junit-platform-isolator-base-8/src/main/java/de/sormuras/junit/platform/isolator/Configuration.java#L292-L317

**Comment by raphw** [comment]
It is. Have a look at how Byte Buddy generates its own hashCode/equals methods.

**Comment by sormuras** [comment]
I'll let IDEA (re-)generate those methods for now:
- local test runs don't need the enhanced classes
- no need to use `@XyzPlug.Enhance` on some classes and therefore introduce a compile (-only) depedency
- `data class X { ... }` will resolve this issue ... soon ... anyway.
